#pragma once

// Generated by QuixiCore/tools/sync_kernel_contract.rb. Do not edit.
// These adapters are scaffolding only and make no implementation claim.

#include <array>

#include "quixicore/contract/kernel_abi.hpp"

namespace quixicore::metal::contract_stubs {

using quixicore::contract::KernelCall;
using quixicore::contract::Status;
using quixicore::contract::StubDescriptor;

[[nodiscard]] inline Status accumulate(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("accumulate", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status act_quant_int8(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("act_quant_int8", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status adamw(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("adamw", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status adamw_masked(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("adamw_masked", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status adaptive_norm_modulation(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("adaptive_norm_modulation", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status adaptive_norm_modulation_qkv(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("adaptive_norm_modulation_qkv", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status adaptive_rms_norm_modulation(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("adaptive_rms_norm_modulation", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status adaptive_rms_norm_modulation_qkv(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("adaptive_rms_norm_modulation_qkv", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status add_id(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("add_id", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status add_relative_position_2d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("add_relative_position_2d", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status add_scalar(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("add_scalar", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status all_gather_gemm(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("all_gather_gemm", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status all_reduce_rms_norm(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("all_reduce_rms_norm", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status arange(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("arange", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status argmax(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("argmax", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status argsort(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("argsort", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status attention(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("attention", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status attention_backward(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("attention_backward", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status attention_gate_residual(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("attention_gate_residual", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status attention_with_lse(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("attention_with_lse", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status audio_conv1d_direct(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("audio_conv1d_direct", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status audio_resample(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("audio_resample", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status based_attention(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("based_attention", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status biased_attention(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("biased_attention", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status broadcast(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("broadcast", "planned family");
}

[[nodiscard]] inline Status causal_conv3d_cache_update(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("causal_conv3d_cache_update", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status causal_conv_gate_residual(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("causal_conv_gate_residual", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status clamp(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("clamp", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status classifier_free_guidance_combine(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("classifier_free_guidance_combine", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status classifier_free_guidance_scheduler_step(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("classifier_free_guidance_scheduler_step", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status col2im_1d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("col2im_1d", "no family claim");
}

[[nodiscard]] inline Status col2im_2d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("col2im_2d", "no family claim");
}

[[nodiscard]] inline Status complex_gemm(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("complex_gemm", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status concat(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("concat", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status conv2d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("conv2d", "no family claim");
}

[[nodiscard]] inline Status conv3d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("conv3d", "no family claim");
}

[[nodiscard]] inline Status conv_transpose_1d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("conv_transpose_1d", "no family claim");
}

[[nodiscard]] inline Status conv_transpose_2d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("conv_transpose_2d", "no family claim");
}

[[nodiscard]] inline Status conv_transpose_overlap_add(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("conv_transpose_overlap_add", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status cosine(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("cosine", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status count_equal(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("count_equal", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status cross_entropy(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("cross_entropy", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status cross_entropy_backward(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("cross_entropy_backward", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status ctc_decode(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("ctc_decode", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status cumulative_sum(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("cumulative_sum", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status decode_linear(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("decode_linear", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status decode_linear_q8(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("decode_linear_q8", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status decode_linear_residual(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("decode_linear_residual", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status deformable_attention(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("deformable_attention", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status dense_gemm(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("dense_gemm", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status dense_gemm_ex(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("dense_gemm_ex", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status depthwise_conv2d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("depthwise_conv2d", "no family claim");
}

[[nodiscard]] inline Status dequant_gather(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("dequant_gather", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status deterministic_noise(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("deterministic_noise", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status diag_embed(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("diag_embed", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status diag_mask(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("diag_mask", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status diffusion_scheduler_step(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("diffusion_scheduler_step", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status divide(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("divide", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status down_projection_residual(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("down_projection_residual", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status downsample_3d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("downsample_3d", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status downsample_conv2d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("downsample_conv2d", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status dropout(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("dropout", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status dsv4_hc_comb(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("dsv4_hc_comb", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status dsv4_hc_post(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("dsv4_hc_post", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status dsv4_hc_pre(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("dsv4_hc_pre", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status embedding_backward(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("embedding_backward", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status embedding_lookup(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("embedding_lookup", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status fake_quant_float8(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("fake_quant_float8", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status fake_quant_int8(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("fake_quant_int8", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status fft_convolution(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("fft_convolution", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status fill(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("fill", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status flow_euler_step(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("flow_euler_step", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status flow_step_action_clamp_denormalize(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("flow_step_action_clamp_denormalize", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status fp8_gemm(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("fp8_gemm", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status fp8_scaled_gemm(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("fp8_scaled_gemm", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status gate_up_projection_swiglu(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("gate_up_projection_swiglu", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status gated_linear_attention(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("gated_linear_attention", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status geglu_projection(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("geglu_projection", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status gelu(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("gelu", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status gelu_backward(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("gelu_backward", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status gemm_gate_residual(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("gemm_gate_residual", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status get_relative_position(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("get_relative_position", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status gguf_gemv(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("gguf_gemv", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status glu(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("glu", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status grammar_mask(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("grammar_mask", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status grid_sample(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("grid_sample", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status group_norm(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("group_norm", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status group_norm_silu(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("group_norm_silu", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status grouped_gemm(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("grouped_gemm", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status hadamard(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("hadamard", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status hedgehog_attention(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("hedgehog_attention", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status im2col_2d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("im2col_2d", "no family claim");
}

[[nodiscard]] inline Status im2col_3d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("im2col_3d", "no family claim");
}

[[nodiscard]] inline Status indexer_k_gather(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("indexer_k_gather", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status int8_gemm(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("int8_gemm", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status istft(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("istft", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status joint_multimodal_attention(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("joint_multimodal_attention", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status kd_ce_fused_bwd(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("kd_ce_fused_bwd", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status kd_ce_fused_fwd(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("kd_ce_fused_fwd", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status kd_kl_dense_bwd(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("kd_kl_dense_bwd", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status kd_kl_dense_fwd(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("kd_kl_dense_fwd", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status kd_kl_topk_bwd(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("kd_kl_topk_bwd", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status kd_kl_topk_fwd(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("kd_kl_topk_fwd", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status kv_cache_compact(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("kv_cache_compact", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status kv_cache_gather(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("kv_cache_gather", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status kv_cache_gather_bitnet_kv3(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("kv_cache_gather_bitnet_kv3", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status kv_cache_offload(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("kv_cache_offload", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status kv_cache_scatter(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("kv_cache_scatter", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status kv_cache_scatter_bitnet_kv3(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("kv_cache_scatter_bitnet_kv3", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status l2_normalize(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("l2_normalize", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status layer_norm(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("layer_norm", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status leaky_relu(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("leaky_relu", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status linear_attention(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("linear_attention", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status linear_attention_unnormalized(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("linear_attention_unnormalized", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status log_mel_spectrogram(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("log_mel_spectrogram", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status logarithm(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("logarithm", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status logits_bias_penalties_top_k_top_p_sample(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("logits_bias_penalties_top_k_top_p_sample", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status lora_apply_direct_f16(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("lora_apply_direct_f16", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status lowbit_gemv(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("lowbit_gemv", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status mamba2_backward(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("mamba2_backward", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status mean_pool_rms_l2(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("mean_pool_rms_l2", "no family claim");
}

[[nodiscard]] inline Status mixed_prefill_decode_attention(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("mixed_prefill_decode_attention", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status moe_all_to_all_dispatch(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("moe_all_to_all_dispatch", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status moe_finalize_backward(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("moe_finalize_backward", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status moe_gather_backward(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("moe_gather_backward", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status moe_grouped_gemm_backward_input(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("moe_grouped_gemm_backward_input", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status moe_grouped_gemm_backward_weight(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("moe_grouped_gemm_backward_weight", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status moe_grouped_gemm_swiglu(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("moe_grouped_gemm_swiglu", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status moe_grouped_qgemm(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("moe_grouped_qgemm", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status moe_grouped_qswiglu(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("moe_grouped_qswiglu", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status moe_route_grouped(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("moe_route_grouped", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status moe_route_top_k_prefix_sum_permute(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("moe_route_top_k_prefix_sum_permute", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status moe_route_topk(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("moe_route_topk", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status moe_unpermute_weighted_reduce(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("moe_unpermute_weighted_reduce", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status multi_codebook_sample(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("multi_codebook_sample", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status multimodal_rope_nd(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("multimodal_rope_nd", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status multimodal_stream_deinterleave(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("multimodal_stream_deinterleave", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status multimodal_stream_interleave(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("multimodal_stream_interleave", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status multiply(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("multiply", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status multistream_logits_codebook_sample(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("multistream_logits_codebook_sample", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status mxfp4_gemv(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("mxfp4_gemv", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status mxfp8_gemm(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("mxfp8_gemm", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status non_max_suppression(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("non_max_suppression", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status norm_quant(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("norm_quant", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status nvfp4_gemm(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("nvfp4_gemm", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status nvfp4_gemv(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("nvfp4_gemv", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status outer_product(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("outer_product", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status overlap_add(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("overlap_add", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status pad_2d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("pad_2d", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status pad_reflect_1d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("pad_reflect_1d", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status paged_attention_advanced(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("paged_attention_advanced", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status paged_attention_bitnet_kv3(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("paged_attention_bitnet_kv3", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status paged_attention_output_projection_residual(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("paged_attention_output_projection_residual", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status paged_attention_turboquant(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("paged_attention_turboquant", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status patch_merge_layer_norm(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("patch_merge_layer_norm", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status patchify_nd(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("patchify_nd", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status patchify_projection_position(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("patchify_projection_position", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status pixel_shuffle(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("pixel_shuffle", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status pool1d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("pool1d", "no family claim");
}

[[nodiscard]] inline Status pool2d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("pool2d", "no family claim");
}

[[nodiscard]] inline Status pool2d_backward(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("pool2d_backward", "no family claim");
}

[[nodiscard]] inline Status prefix_append_attention(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("prefix_append_attention", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status qgeglu(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("qgeglu", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status qgemm(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("qgemm", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status qgemm_backward_input(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("qgemm_backward_input", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status qgemm_int(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("qgemm_int", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status qgemm_q4q8(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("qgemm_q4q8", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status qgemv(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("qgemv", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status qgemv_qkv(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("qgemv_qkv", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status qgemv_up_gate(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("qgemv_up_gate", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status qgemv_up_gate_activation(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("qgemv_up_gate_activation", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status qk_norm_rope(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("qk_norm_rope", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status qk_norm_rope_attention(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("qk_norm_rope_attention", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status qkv_proj_fused(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("qkv_proj_fused", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status qkv_projection_qk_norm_rope_kv_append(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("qkv_projection_qk_norm_rope_kv_append", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status quantize_int4_group(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("quantize_int4_group", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status quantized_attention(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("quantized_attention", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status quantized_lm_head_sample(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("quantized_lm_head_sample", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status ragged_pack(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("ragged_pack", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status ragged_unpack(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("ragged_unpack", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status reduce_mean(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("reduce_mean", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status reduce_scatter_gemm(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("reduce_scatter_gemm", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status reduce_sum(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("reduce_sum", "planned family");
}

[[nodiscard]] inline Status reduce_sum_all(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("reduce_sum_all", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status repeat_2d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("repeat_2d", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status repeat_backward_2d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("repeat_backward_2d", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status residual_rms_norm_quant(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("residual_rms_norm_quant", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status residual_vector_quantize_decode(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("residual_vector_quantize_decode", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status residual_vector_quantize_encode(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("residual_vector_quantize_encode", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status resize_bicubic(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("resize_bicubic", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status resize_bilinear(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("resize_bilinear", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status resize_normalize_layout_quant(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("resize_normalize_layout_quant", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status rms_norm(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("rms_norm", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status rms_norm_backward(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("rms_norm_backward", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status rms_norm_residual_next(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("rms_norm_residual_next", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status rnnt_beam_step(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("rnnt_beam_step", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status rnnt_joiner(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("rnnt_joiner", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status roi_align(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("roi_align", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status roll_2d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("roll_2d", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status rope(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("rope", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status rope_3d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("rope_3d", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status rvq_distance_argmin_residual_update(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("rvq_distance_argmin_residual_update", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status rwkv_wkv6(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("rwkv_wkv6", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status rwkv_wkv7(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("rwkv_wkv7", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status sample_categorical(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("sample_categorical", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status scale(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("scale", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status selective_scan(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("selective_scan", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status set_rows(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("set_rows", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status sgd(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("sgd", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status sigmoid_mul_backward(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("sigmoid_mul_backward", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status silu(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("silu", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status silu_backward(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("silu_backward", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status sine(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("sine", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status softmax(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("softmax", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status softmax_backward(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("softmax_backward", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status solve_lower_triangular(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("solve_lower_triangular", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status speculative_verify_accept_compact_kv(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("speculative_verify_accept_compact_kv", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status square(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("square", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status square_root(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("square_root", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status ssd_chunked_backward(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("ssd_chunked_backward", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status ssd_decode(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("ssd_decode", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status stft(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("stft", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status streaming_conv1d_state(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("streaming_conv1d_state", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status subtract(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("subtract", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status swiglu_oai(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("swiglu_oai", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status temporal_upsample_conv3d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("temporal_upsample_conv3d", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status tensor_copy(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("tensor_copy", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status tensor_set_4d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("tensor_set_4d", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status ternary_code_flip_count(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("ternary_code_flip_count", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status ternary_pack(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("ternary_pack", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status ternary_stats(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("ternary_stats", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status ternary_unpack(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("ternary_unpack", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status threshold_topk_indices(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("threshold_topk_indices", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status timestep_embedding(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("timestep_embedding", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status top_k_renorm(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("top_k_renorm", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status top_k_sample(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("top_k_sample", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status top_p_renorm(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("top_p_renorm", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status tq2_0_pack(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("tq2_0_pack", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status tq2_0_unpack(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("tq2_0_unpack", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status triangular_fill(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("triangular_fill", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status turboquant(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("turboquant", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status unary(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("unary", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status unpatchify_nd(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("unpatchify_nd", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status upsample_3d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("upsample_3d", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status upsample_conv2d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("upsample_conv2d", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status upscale_nearest_2d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("upscale_nearest_2d", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status window_attention(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("window_attention", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status window_partition(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("window_partition", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status window_rfft_power_mel_log(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("window_rfft_power_mel_log", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status window_unpartition(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("window_unpartition", "family-only metadata; canonical adapter not wired");
}

inline constexpr std::array<StubDescriptor, 250> kStubs{{
    {"accumulate", "utils", "family-only metadata; canonical adapter not wired", &accumulate},
    {"act_quant_int8", "quantization", "family-only metadata; canonical adapter not wired", &act_quant_int8},
    {"adamw", "optimizers", "family-only metadata; canonical adapter not wired", &adamw},
    {"adamw_masked", "optimizers", "family-only metadata; canonical adapter not wired", &adamw_masked},
    {"adaptive_norm_modulation", "diffusion", "planned contract; no backend implementation evidence", &adaptive_norm_modulation},
    {"adaptive_norm_modulation_qkv", "diffusion", "planned contract; no backend implementation evidence", &adaptive_norm_modulation_qkv},
    {"adaptive_rms_norm_modulation", "diffusion", "planned contract; no backend implementation evidence", &adaptive_rms_norm_modulation},
    {"adaptive_rms_norm_modulation_qkv", "diffusion", "planned contract; no backend implementation evidence", &adaptive_rms_norm_modulation_qkv},
    {"add_id", "utils", "family-only metadata; canonical adapter not wired", &add_id},
    {"add_relative_position_2d", "vision", "family-only metadata; canonical adapter not wired", &add_relative_position_2d},
    {"add_scalar", "utils", "family-only metadata; canonical adapter not wired", &add_scalar},
    {"all_gather_gemm", "collectives", "planned contract; no backend implementation evidence", &all_gather_gemm},
    {"all_reduce_rms_norm", "collectives", "planned contract; no backend implementation evidence", &all_reduce_rms_norm},
    {"arange", "utils", "family-only metadata; canonical adapter not wired", &arange},
    {"argmax", "sampling", "family-only metadata; canonical adapter not wired", &argmax},
    {"argsort", "utils", "family-only metadata; canonical adapter not wired", &argsort},
    {"attention", "attention", "family-only metadata; canonical adapter not wired", &attention},
    {"attention_backward", "attention", "family-only metadata; canonical adapter not wired", &attention_backward},
    {"attention_gate_residual", "attention", "planned contract; no backend implementation evidence", &attention_gate_residual},
    {"attention_with_lse", "attention", "family-only metadata; canonical adapter not wired", &attention_with_lse},
    {"audio_conv1d_direct", "audio", "family-only metadata; canonical adapter not wired", &audio_conv1d_direct},
    {"audio_resample", "audio", "planned contract; no backend implementation evidence", &audio_resample},
    {"based_attention", "linear_attention", "family-only metadata; canonical adapter not wired", &based_attention},
    {"biased_attention", "attention", "family-only metadata; canonical adapter not wired", &biased_attention},
    {"broadcast", "collectives", "planned family", &broadcast},
    {"causal_conv3d_cache_update", "convolution", "planned contract; no backend implementation evidence", &causal_conv3d_cache_update},
    {"causal_conv_gate_residual", "audio", "planned contract; no backend implementation evidence", &causal_conv_gate_residual},
    {"clamp", "utils", "family-only metadata; canonical adapter not wired", &clamp},
    {"classifier_free_guidance_combine", "diffusion", "planned contract; no backend implementation evidence", &classifier_free_guidance_combine},
    {"classifier_free_guidance_scheduler_step", "diffusion", "planned contract; no backend implementation evidence", &classifier_free_guidance_scheduler_step},
    {"col2im_1d", "convolution", "no family claim", &col2im_1d},
    {"col2im_2d", "convolution", "no family claim", &col2im_2d},
    {"complex_gemm", "matmul", "family-only metadata; canonical adapter not wired", &complex_gemm},
    {"concat", "utils", "family-only metadata; canonical adapter not wired", &concat},
    {"conv2d", "convolution", "no family claim", &conv2d},
    {"conv3d", "convolution", "no family claim", &conv3d},
    {"conv_transpose_1d", "convolution", "no family claim", &conv_transpose_1d},
    {"conv_transpose_2d", "convolution", "no family claim", &conv_transpose_2d},
    {"conv_transpose_overlap_add", "audio", "planned contract; no backend implementation evidence", &conv_transpose_overlap_add},
    {"cosine", "utils", "family-only metadata; canonical adapter not wired", &cosine},
    {"count_equal", "utils", "family-only metadata; canonical adapter not wired", &count_equal},
    {"cross_entropy", "utils", "family-only metadata; canonical adapter not wired", &cross_entropy},
    {"cross_entropy_backward", "utils", "family-only metadata; canonical adapter not wired", &cross_entropy_backward},
    {"ctc_decode", "audio", "planned contract; no backend implementation evidence", &ctc_decode},
    {"cumulative_sum", "utils", "family-only metadata; canonical adapter not wired", &cumulative_sum},
    {"decode_linear", "matmul", "family-only metadata; canonical adapter not wired", &decode_linear},
    {"decode_linear_q8", "matmul", "family-only metadata; canonical adapter not wired", &decode_linear_q8},
    {"decode_linear_residual", "matmul", "family-only metadata; canonical adapter not wired", &decode_linear_residual},
    {"deformable_attention", "vision", "planned contract; no backend implementation evidence", &deformable_attention},
    {"dense_gemm", "matmul", "family-only metadata; canonical adapter not wired", &dense_gemm},
    {"dense_gemm_ex", "matmul", "family-only metadata; canonical adapter not wired", &dense_gemm_ex},
    {"depthwise_conv2d", "convolution", "no family claim", &depthwise_conv2d},
    {"dequant_gather", "quantization", "family-only metadata; canonical adapter not wired", &dequant_gather},
    {"deterministic_noise", "diffusion", "planned contract; no backend implementation evidence", &deterministic_noise},
    {"diag_embed", "utils", "family-only metadata; canonical adapter not wired", &diag_embed},
    {"diag_mask", "utils", "family-only metadata; canonical adapter not wired", &diag_mask},
    {"diffusion_scheduler_step", "diffusion", "planned contract; no backend implementation evidence", &diffusion_scheduler_step},
    {"divide", "utils", "family-only metadata; canonical adapter not wired", &divide},
    {"down_projection_residual", "matmul", "planned contract; no backend implementation evidence", &down_projection_residual},
    {"downsample_3d", "convolution", "planned contract; no backend implementation evidence", &downsample_3d},
    {"downsample_conv2d", "convolution", "planned contract; no backend implementation evidence", &downsample_conv2d},
    {"dropout", "utils", "family-only metadata; canonical adapter not wired", &dropout},
    {"dsv4_hc_comb", "ssm", "family-only metadata; canonical adapter not wired", &dsv4_hc_comb},
    {"dsv4_hc_post", "ssm", "family-only metadata; canonical adapter not wired", &dsv4_hc_post},
    {"dsv4_hc_pre", "ssm", "family-only metadata; canonical adapter not wired", &dsv4_hc_pre},
    {"embedding_backward", "serving", "family-only metadata; canonical adapter not wired", &embedding_backward},
    {"embedding_lookup", "serving", "family-only metadata; canonical adapter not wired", &embedding_lookup},
    {"fake_quant_float8", "quantization", "family-only metadata; canonical adapter not wired", &fake_quant_float8},
    {"fake_quant_int8", "quantization", "family-only metadata; canonical adapter not wired", &fake_quant_int8},
    {"fft_convolution", "ssm", "family-only metadata; canonical adapter not wired", &fft_convolution},
    {"fill", "utils", "family-only metadata; canonical adapter not wired", &fill},
    {"flow_euler_step", "diffusion", "planned contract; no backend implementation evidence", &flow_euler_step},
    {"flow_step_action_clamp_denormalize", "vla_world_models", "planned contract; no backend implementation evidence", &flow_step_action_clamp_denormalize},
    {"fp8_gemm", "quantization", "family-only metadata; canonical adapter not wired", &fp8_gemm},
    {"fp8_scaled_gemm", "matmul", "family-only metadata; canonical adapter not wired", &fp8_scaled_gemm},
    {"gate_up_projection_swiglu", "matmul", "planned contract; no backend implementation evidence", &gate_up_projection_swiglu},
    {"gated_linear_attention", "linear_attention", "family-only metadata; canonical adapter not wired", &gated_linear_attention},
    {"geglu_projection", "matmul", "planned contract; no backend implementation evidence", &geglu_projection},
    {"gelu", "activations", "family-only metadata; canonical adapter not wired", &gelu},
    {"gelu_backward", "activations", "family-only metadata; canonical adapter not wired", &gelu_backward},
    {"gemm_gate_residual", "matmul", "family-only metadata; canonical adapter not wired", &gemm_gate_residual},
    {"get_relative_position", "vision", "family-only metadata; canonical adapter not wired", &get_relative_position},
    {"gguf_gemv", "quantization", "family-only metadata; canonical adapter not wired", &gguf_gemv},
    {"glu", "activations", "family-only metadata; canonical adapter not wired", &glu},
    {"grammar_mask", "sampling", "planned contract; no backend implementation evidence", &grammar_mask},
    {"grid_sample", "vision", "planned contract; no backend implementation evidence", &grid_sample},
    {"group_norm", "utils", "family-only metadata; canonical adapter not wired", &group_norm},
    {"group_norm_silu", "convolution", "planned contract; no backend implementation evidence", &group_norm_silu},
    {"grouped_gemm", "matmul", "family-only metadata; canonical adapter not wired", &grouped_gemm},
    {"hadamard", "utils", "family-only metadata; canonical adapter not wired", &hadamard},
    {"hedgehog_attention", "linear_attention", "family-only metadata; canonical adapter not wired", &hedgehog_attention},
    {"im2col_2d", "convolution", "no family claim", &im2col_2d},
    {"im2col_3d", "convolution", "no family claim", &im2col_3d},
    {"indexer_k_gather", "serving", "family-only metadata; canonical adapter not wired", &indexer_k_gather},
    {"int8_gemm", "matmul", "family-only metadata; canonical adapter not wired", &int8_gemm},
    {"istft", "audio", "planned contract; no backend implementation evidence", &istft},
    {"joint_multimodal_attention", "multimodal", "planned contract; no backend implementation evidence", &joint_multimodal_attention},
    {"kd_ce_fused_bwd", "utils", "family-only metadata; canonical adapter not wired", &kd_ce_fused_bwd},
    {"kd_ce_fused_fwd", "utils", "family-only metadata; canonical adapter not wired", &kd_ce_fused_fwd},
    {"kd_kl_dense_bwd", "utils", "family-only metadata; canonical adapter not wired", &kd_kl_dense_bwd},
    {"kd_kl_dense_fwd", "utils", "family-only metadata; canonical adapter not wired", &kd_kl_dense_fwd},
    {"kd_kl_topk_bwd", "utils", "family-only metadata; canonical adapter not wired", &kd_kl_topk_bwd},
    {"kd_kl_topk_fwd", "utils", "family-only metadata; canonical adapter not wired", &kd_kl_topk_fwd},
    {"kv_cache_compact", "serving", "planned contract; no backend implementation evidence", &kv_cache_compact},
    {"kv_cache_gather", "serving", "family-only metadata; canonical adapter not wired", &kv_cache_gather},
    {"kv_cache_gather_bitnet_kv3", "serving", "family-only metadata; canonical adapter not wired", &kv_cache_gather_bitnet_kv3},
    {"kv_cache_offload", "serving", "planned contract; no backend implementation evidence", &kv_cache_offload},
    {"kv_cache_scatter", "serving", "family-only metadata; canonical adapter not wired", &kv_cache_scatter},
    {"kv_cache_scatter_bitnet_kv3", "serving", "family-only metadata; canonical adapter not wired", &kv_cache_scatter_bitnet_kv3},
    {"l2_normalize", "utils", "family-only metadata; canonical adapter not wired", &l2_normalize},
    {"layer_norm", "norms", "family-only metadata; canonical adapter not wired", &layer_norm},
    {"leaky_relu", "activations", "family-only metadata; canonical adapter not wired", &leaky_relu},
    {"linear_attention", "linear_attention", "family-only metadata; canonical adapter not wired", &linear_attention},
    {"linear_attention_unnormalized", "linear_attention", "family-only metadata; canonical adapter not wired", &linear_attention_unnormalized},
    {"log_mel_spectrogram", "audio", "planned contract; no backend implementation evidence", &log_mel_spectrogram},
    {"logarithm", "utils", "family-only metadata; canonical adapter not wired", &logarithm},
    {"logits_bias_penalties_top_k_top_p_sample", "sampling", "planned contract; no backend implementation evidence", &logits_bias_penalties_top_k_top_p_sample},
    {"lora_apply_direct_f16", "matmul", "family-only metadata; canonical adapter not wired", &lora_apply_direct_f16},
    {"lowbit_gemv", "quantization", "family-only metadata; canonical adapter not wired", &lowbit_gemv},
    {"mamba2_backward", "ssm", "family-only metadata; canonical adapter not wired", &mamba2_backward},
    {"mean_pool_rms_l2", "pooling", "no family claim", &mean_pool_rms_l2},
    {"mixed_prefill_decode_attention", "attention", "planned contract; no backend implementation evidence", &mixed_prefill_decode_attention},
    {"moe_all_to_all_dispatch", "collectives", "planned contract; no backend implementation evidence", &moe_all_to_all_dispatch},
    {"moe_finalize_backward", "moe", "family-only metadata; canonical adapter not wired", &moe_finalize_backward},
    {"moe_gather_backward", "moe", "family-only metadata; canonical adapter not wired", &moe_gather_backward},
    {"moe_grouped_gemm_backward_input", "moe", "family-only metadata; canonical adapter not wired", &moe_grouped_gemm_backward_input},
    {"moe_grouped_gemm_backward_weight", "moe", "family-only metadata; canonical adapter not wired", &moe_grouped_gemm_backward_weight},
    {"moe_grouped_gemm_swiglu", "moe", "planned contract; no backend implementation evidence", &moe_grouped_gemm_swiglu},
    {"moe_grouped_qgemm", "moe", "family-only metadata; canonical adapter not wired", &moe_grouped_qgemm},
    {"moe_grouped_qswiglu", "moe", "family-only metadata; canonical adapter not wired", &moe_grouped_qswiglu},
    {"moe_route_grouped", "moe", "family-only metadata; canonical adapter not wired", &moe_route_grouped},
    {"moe_route_top_k_prefix_sum_permute", "moe", "planned contract; no backend implementation evidence", &moe_route_top_k_prefix_sum_permute},
    {"moe_route_topk", "moe", "family-only metadata; canonical adapter not wired", &moe_route_topk},
    {"moe_unpermute_weighted_reduce", "moe", "planned contract; no backend implementation evidence", &moe_unpermute_weighted_reduce},
    {"multi_codebook_sample", "audio", "planned contract; no backend implementation evidence", &multi_codebook_sample},
    {"multimodal_rope_nd", "multimodal", "planned contract; no backend implementation evidence", &multimodal_rope_nd},
    {"multimodal_stream_deinterleave", "multimodal", "planned contract; no backend implementation evidence", &multimodal_stream_deinterleave},
    {"multimodal_stream_interleave", "multimodal", "planned contract; no backend implementation evidence", &multimodal_stream_interleave},
    {"multiply", "utils", "family-only metadata; canonical adapter not wired", &multiply},
    {"multistream_logits_codebook_sample", "audio", "planned contract; no backend implementation evidence", &multistream_logits_codebook_sample},
    {"mxfp4_gemv", "quantization", "family-only metadata; canonical adapter not wired", &mxfp4_gemv},
    {"mxfp8_gemm", "matmul", "family-only metadata; canonical adapter not wired", &mxfp8_gemm},
    {"non_max_suppression", "vision", "planned contract; no backend implementation evidence", &non_max_suppression},
    {"norm_quant", "norms", "family-only metadata; canonical adapter not wired", &norm_quant},
    {"nvfp4_gemm", "matmul", "family-only metadata; canonical adapter not wired", &nvfp4_gemm},
    {"nvfp4_gemv", "quantization", "family-only metadata; canonical adapter not wired", &nvfp4_gemv},
    {"outer_product", "utils", "family-only metadata; canonical adapter not wired", &outer_product},
    {"overlap_add", "audio", "planned contract; no backend implementation evidence", &overlap_add},
    {"pad_2d", "utils", "family-only metadata; canonical adapter not wired", &pad_2d},
    {"pad_reflect_1d", "utils", "family-only metadata; canonical adapter not wired", &pad_reflect_1d},
    {"paged_attention_advanced", "serving", "family-only metadata; canonical adapter not wired", &paged_attention_advanced},
    {"paged_attention_bitnet_kv3", "serving", "family-only metadata; canonical adapter not wired", &paged_attention_bitnet_kv3},
    {"paged_attention_output_projection_residual", "attention", "planned contract; no backend implementation evidence", &paged_attention_output_projection_residual},
    {"paged_attention_turboquant", "serving", "family-only metadata; canonical adapter not wired", &paged_attention_turboquant},
    {"patch_merge_layer_norm", "vision", "family-only metadata; canonical adapter not wired", &patch_merge_layer_norm},
    {"patchify_nd", "diffusion", "planned contract; no backend implementation evidence", &patchify_nd},
    {"patchify_projection_position", "vision", "planned contract; no backend implementation evidence", &patchify_projection_position},
    {"pixel_shuffle", "vision", "planned contract; no backend implementation evidence", &pixel_shuffle},
    {"pool1d", "convolution", "no family claim", &pool1d},
    {"pool2d", "convolution", "no family claim", &pool2d},
    {"pool2d_backward", "convolution", "no family claim", &pool2d_backward},
    {"prefix_append_attention", "attention", "planned contract; no backend implementation evidence", &prefix_append_attention},
    {"qgeglu", "quantization", "family-only metadata; canonical adapter not wired", &qgeglu},
    {"qgemm", "quantization", "family-only metadata; canonical adapter not wired", &qgemm},
    {"qgemm_backward_input", "quantization", "family-only metadata; canonical adapter not wired", &qgemm_backward_input},
    {"qgemm_int", "quantization", "family-only metadata; canonical adapter not wired", &qgemm_int},
    {"qgemm_q4q8", "quantization", "family-only metadata; canonical adapter not wired", &qgemm_q4q8},
    {"qgemv", "quantization", "family-only metadata; canonical adapter not wired", &qgemv},
    {"qgemv_qkv", "quantization", "family-only metadata; canonical adapter not wired", &qgemv_qkv},
    {"qgemv_up_gate", "quantization", "family-only metadata; canonical adapter not wired", &qgemv_up_gate},
    {"qgemv_up_gate_activation", "quantization", "family-only metadata; canonical adapter not wired", &qgemv_up_gate_activation},
    {"qk_norm_rope", "norms", "family-only metadata; canonical adapter not wired", &qk_norm_rope},
    {"qk_norm_rope_attention", "attention", "planned contract; no backend implementation evidence", &qk_norm_rope_attention},
    {"qkv_proj_fused", "quantization", "family-only metadata; canonical adapter not wired", &qkv_proj_fused},
    {"qkv_projection_qk_norm_rope_kv_append", "attention", "planned contract; no backend implementation evidence", &qkv_projection_qk_norm_rope_kv_append},
    {"quantize_int4_group", "quantization", "family-only metadata; canonical adapter not wired", &quantize_int4_group},
    {"quantized_attention", "serving", "family-only metadata; canonical adapter not wired", &quantized_attention},
    {"quantized_lm_head_sample", "quantization", "family-only metadata; canonical adapter not wired", &quantized_lm_head_sample},
    {"ragged_pack", "multimodal", "planned contract; no backend implementation evidence", &ragged_pack},
    {"ragged_unpack", "multimodal", "planned contract; no backend implementation evidence", &ragged_unpack},
    {"reduce_mean", "utils", "family-only metadata; canonical adapter not wired", &reduce_mean},
    {"reduce_scatter_gemm", "collectives", "planned contract; no backend implementation evidence", &reduce_scatter_gemm},
    {"reduce_sum", "collectives", "planned family", &reduce_sum},
    {"reduce_sum_all", "utils", "family-only metadata; canonical adapter not wired", &reduce_sum_all},
    {"repeat_2d", "utils", "family-only metadata; canonical adapter not wired", &repeat_2d},
    {"repeat_backward_2d", "utils", "family-only metadata; canonical adapter not wired", &repeat_backward_2d},
    {"residual_rms_norm_quant", "norms", "planned contract; no backend implementation evidence", &residual_rms_norm_quant},
    {"residual_vector_quantize_decode", "audio", "planned contract; no backend implementation evidence", &residual_vector_quantize_decode},
    {"residual_vector_quantize_encode", "audio", "planned contract; no backend implementation evidence", &residual_vector_quantize_encode},
    {"resize_bicubic", "vision", "planned contract; no backend implementation evidence", &resize_bicubic},
    {"resize_bilinear", "vision", "planned contract; no backend implementation evidence", &resize_bilinear},
    {"resize_normalize_layout_quant", "vision", "planned contract; no backend implementation evidence", &resize_normalize_layout_quant},
    {"rms_norm", "norms", "family-only metadata; canonical adapter not wired", &rms_norm},
    {"rms_norm_backward", "norms", "family-only metadata; canonical adapter not wired", &rms_norm_backward},
    {"rms_norm_residual_next", "norms", "family-only metadata; canonical adapter not wired", &rms_norm_residual_next},
    {"rnnt_beam_step", "audio", "planned contract; no backend implementation evidence", &rnnt_beam_step},
    {"rnnt_joiner", "audio", "planned contract; no backend implementation evidence", &rnnt_joiner},
    {"roi_align", "vision", "planned contract; no backend implementation evidence", &roi_align},
    {"roll_2d", "utils", "family-only metadata; canonical adapter not wired", &roll_2d},
    {"rope", "attention", "family-only metadata; canonical adapter not wired", &rope},
    {"rope_3d", "diffusion", "planned contract; no backend implementation evidence", &rope_3d},
    {"rvq_distance_argmin_residual_update", "audio", "planned contract; no backend implementation evidence", &rvq_distance_argmin_residual_update},
    {"rwkv_wkv6", "linear_attention", "family-only metadata; canonical adapter not wired", &rwkv_wkv6},
    {"rwkv_wkv7", "linear_attention", "family-only metadata; canonical adapter not wired", &rwkv_wkv7},
    {"sample_categorical", "sampling", "family-only metadata; canonical adapter not wired", &sample_categorical},
    {"scale", "utils", "family-only metadata; canonical adapter not wired", &scale},
    {"selective_scan", "ssm", "family-only metadata; canonical adapter not wired", &selective_scan},
    {"set_rows", "utils", "family-only metadata; canonical adapter not wired", &set_rows},
    {"sgd", "optimizers", "family-only metadata; canonical adapter not wired", &sgd},
    {"sigmoid_mul_backward", "activations", "family-only metadata; canonical adapter not wired", &sigmoid_mul_backward},
    {"silu", "activations", "family-only metadata; canonical adapter not wired", &silu},
    {"silu_backward", "activations", "family-only metadata; canonical adapter not wired", &silu_backward},
    {"sine", "utils", "family-only metadata; canonical adapter not wired", &sine},
    {"softmax", "activations", "family-only metadata; canonical adapter not wired", &softmax},
    {"softmax_backward", "activations", "family-only metadata; canonical adapter not wired", &softmax_backward},
    {"solve_lower_triangular", "utils", "family-only metadata; canonical adapter not wired", &solve_lower_triangular},
    {"speculative_verify_accept_compact_kv", "serving", "planned contract; no backend implementation evidence", &speculative_verify_accept_compact_kv},
    {"square", "utils", "family-only metadata; canonical adapter not wired", &square},
    {"square_root", "utils", "family-only metadata; canonical adapter not wired", &square_root},
    {"ssd_chunked_backward", "ssm", "family-only metadata; canonical adapter not wired", &ssd_chunked_backward},
    {"ssd_decode", "ssm", "family-only metadata; canonical adapter not wired", &ssd_decode},
    {"stft", "audio", "planned contract; no backend implementation evidence", &stft},
    {"streaming_conv1d_state", "audio", "planned contract; no backend implementation evidence", &streaming_conv1d_state},
    {"subtract", "utils", "family-only metadata; canonical adapter not wired", &subtract},
    {"swiglu_oai", "activations", "family-only metadata; canonical adapter not wired", &swiglu_oai},
    {"temporal_upsample_conv3d", "convolution", "planned contract; no backend implementation evidence", &temporal_upsample_conv3d},
    {"tensor_copy", "utils", "family-only metadata; canonical adapter not wired", &tensor_copy},
    {"tensor_set_4d", "utils", "family-only metadata; canonical adapter not wired", &tensor_set_4d},
    {"ternary_code_flip_count", "quantization", "family-only metadata; canonical adapter not wired", &ternary_code_flip_count},
    {"ternary_pack", "quantization", "family-only metadata; canonical adapter not wired", &ternary_pack},
    {"ternary_stats", "quantization", "family-only metadata; canonical adapter not wired", &ternary_stats},
    {"ternary_unpack", "quantization", "family-only metadata; canonical adapter not wired", &ternary_unpack},
    {"threshold_topk_indices", "utils", "family-only metadata; canonical adapter not wired", &threshold_topk_indices},
    {"timestep_embedding", "vision", "family-only metadata; canonical adapter not wired", &timestep_embedding},
    {"top_k_renorm", "sampling", "family-only metadata; canonical adapter not wired", &top_k_renorm},
    {"top_k_sample", "sampling", "family-only metadata; canonical adapter not wired", &top_k_sample},
    {"top_p_renorm", "sampling", "family-only metadata; canonical adapter not wired", &top_p_renorm},
    {"tq2_0_pack", "quantization", "family-only metadata; canonical adapter not wired", &tq2_0_pack},
    {"tq2_0_unpack", "quantization", "family-only metadata; canonical adapter not wired", &tq2_0_unpack},
    {"triangular_fill", "utils", "family-only metadata; canonical adapter not wired", &triangular_fill},
    {"turboquant", "quantization", "family-only metadata; canonical adapter not wired", &turboquant},
    {"unary", "activations", "family-only metadata; canonical adapter not wired", &unary},
    {"unpatchify_nd", "diffusion", "planned contract; no backend implementation evidence", &unpatchify_nd},
    {"upsample_3d", "convolution", "planned contract; no backend implementation evidence", &upsample_3d},
    {"upsample_conv2d", "convolution", "planned contract; no backend implementation evidence", &upsample_conv2d},
    {"upscale_nearest_2d", "vision", "family-only metadata; canonical adapter not wired", &upscale_nearest_2d},
    {"window_attention", "attention", "family-only metadata; canonical adapter not wired", &window_attention},
    {"window_partition", "vision", "family-only metadata; canonical adapter not wired", &window_partition},
    {"window_rfft_power_mel_log", "audio", "planned contract; no backend implementation evidence", &window_rfft_power_mel_log},
    {"window_unpartition", "vision", "family-only metadata; canonical adapter not wired", &window_unpartition},
}};

}  // namespace quixicore::metal::contract_stubs
